version: 2

updates:
  - package-ecosystem: 'maven'
    directory: "/"
    schudule: 
      interval: "weekly"

  - package-ecosystem: 'docker'
    directory: "/"
    schudule: 
      interval: "weekly"
